steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/homecare360-465809/gateway/production',
        '-f',
        'apps/gateway/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/homecare360-465809/gateway/production',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'restart', 'deployment/gateway']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
      - 'CLOUDSDK_CORE_PROJECT=homecare360-465809'
options:
  logging: CLOUD_LOGGING_ONLY
